import glob
import os
import platform
import re
import shutil
import subprocess

from setuptools import setup, Extension
import setuptools.command.build_py

UTM_VERSION = "0.14.0"
PACKAGE_NAME = "tmGrammar"
PACKAGE_DIR = os.path.realpath(os.path.join(os.path.dirname(__file__), PACKAGE_NAME))

UTM_BASE = os.environ.get("UTM_BASE")
if not UTM_BASE:
    raise RuntimeError("UTM_BASE not defined")

BOOST_BASE = os.environ.get("BOOST_BASE", "")


class BuildPyCommand(setuptools.command.build_py.build_py):
    """Custom build command."""

    def create_swig_wrapper(self):
        command = []
        subprocess.check_call([
            "swig",
            "-c++",
            "-python",
            "-I{}".format(os.path.join(BOOST_BASE, "include")),
            "-I{}".format(os.path.join(UTM_BASE, "include")),
            os.path.join(PACKAGE_DIR, f"{PACKAGE_NAME}.i"),
        ])

    def create_version_module(self):
        with open(os.path.join(PACKAGE_DIR, "_version.py"), "w") as f:
            f.write("# This file was auto generated by `setup.py`, changes might be lost.\n")
            f.write(f"__version__ = \"{UTM_VERSION}\"\n")

    def run(self):
        self.create_swig_wrapper()
        self.create_version_module()
        # run actual build command
        setuptools.command.build_py.build_py.run(self)


def get_extra_link_args():
    extra_link_args = []
    if platform.system() == "Darwin":
        extra_link_args.append("-Wl,-headerpad_max_install_names")  # macos install_name_tool issues
    return extra_link_args


tmGrammar_ext = Extension(
    name="_tmGrammar",
    define_macros=[("SWIG", "1"), ("DNDEBUG", "1")],
    sources=[
        os.path.join("tmGrammar", "tmGrammar_wrap.cxx")
    ],
    include_dirs=[
        os.path.join(BOOST_BASE, "include"),
        os.path.join(UTM_BASE, "include"),
    ],
    library_dirs=[
        os.path.join(BOOST_BASE, "lib"),
        os.path.join(UTM_BASE, "lib"),
    ],
    libraries=["tmutil", "tmgrammar"],
    extra_compile_args=["-std=c++11", "-O2"],
    extra_link_args=get_extra_link_args()
)

setup(
    version=UTM_VERSION,
    ext_modules=[tmGrammar_ext],
    cmdclass={
        "build_py": BuildPyCommand,
    },
    packages=[PACKAGE_NAME],
    package_data={
        PACKAGE_NAME: [
            f"{PACKAGE_NAME}.i",
        ]
    }
)
